'load_main_model': False
'save_model': True
'model': {'type': 'wresnet28_10'}
dataset: cifar10
'aug': 'randaugment'
'randaug': {'N': 0, 'M': 0, 'weights': [0.0,1.0]}
'augmentation_search_space': 'fix_custom'
'cutout': 16
'batch': 128
'gpus': 1
'seed': 2022
lr: 0.05
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
'throwaway_share_of_ds': {'throwaway_share': .2,'use_throwaway_as_val': True}