model:
  type: efficientnet-b0
dataset: smallwidth_imagenet
aug: randaugment
augmentation_search_space: fixed_standard # they used 224 x 244
randaug:
  N: 0
  M: 0
  weights: [0.0,1.0]
cutout: 0
batch: 64
gpus: 32
epoch: 270
lr: .256
lr_schedule:
  type: 'exponential'
  gamma: 0.9873888589
optimizer:
  type: rmsprop
  decay: 1.0e-5
  alpha: 0.9
  momentum: 0.9
  clip: 0

