model:
  type: miniconvnet
dataset: cifar100
aug: default
augmentation_search_space: long_wide
cutout: 16
batch: 256
epoch: 100
lr: 0.05

lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5

optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

finite_difference_loss: true

preprocessor:
  type: learned_1x1conv
  hidden_dim: 0
  uniaug_val: false
  oldpreprocessor_val: false

meta_opt:
  meta_optimizer:
    type: sgd
    lr: .001
    beta1: .9
    beta2: .999
