model:
  type: wresnet28_10
dataset: cifar10
augmentation_search_space: randaug_standard
cutout: 16
batch: 64
gpus: 4
epoch: 100
lr: 0.05
aug: randaugment
randaug:
  N: 0
  M: 0
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005


throwaway_share_of_ds: .2
