model:
  type: resnet50
dataset: imagenet
aug: randaugment
augmentation_search_space: fixed_standard
randaug:
  N: 0
  M: 0    # from appendix
cutout: 0
batch: 32
gpus: 8
epoch: 270
lr: 0.1
lr_schedule:
  type: 'resnet'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0

