model:
  type: resnet50
dataset: imagenet
aug: default
cutout: 0
gpus: 8
batch: 64
epoch: 270
lr: 1.6
lr_schedule:
  type: 'resnet'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0
  clip: 0
step_optimizer_every: 8
step_optimizer_nth_step: 7
communicate_grad_every: 8
