model:
  type: resnet50
dataset: imagenet
aug: randaugment
augmentation_search_space: uniaug
randaug:
  N: 0
  M: 0
cutout: 0
batch: 100
gpus: 64
epoch: 270  # 270
lr: 0.1
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 3
    epoch: 3
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
