model:
  type: resnet50
preprocessor:
  type: standard
dataset: imagenet
aug: default
cutout: 0
batch: 64
gpus: 8
epoch: 270
lr: 0.2
lr_schedule:
  type: 'resnet'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0


