model:
  type: resnet50
dataset: imagenet
aug: randaugment
randaug:
  N: 1
  M: 15
cutout: 0
batch: 128
gpus: 8
epoch: 270  # 270
lr: 0.0125
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 4
    epoch: 3
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0