model:
  type: resnet50
dataset: imagenet
aug: randaugment
augmentation_search_space: fixed_standard
randaug:
  N: 0
  M: 0
  weights: [0.0,1.0]
cutout: 0
batch: 100
gpus: 8
epoch: 180
lr: 0.125
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 3
    epoch: 3
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0

step_optimizer_every: 2
step_optimizer_nth_step: 1
communicate_grad_every: 2
