all_workers_use_the_same_batches: true
model:
  type: shakeshake26_2x96d
dataset: cifar100
cutout: 16
batch: 128
epoch: 1200
gpus: 8
lr: 0.1
aug: randaugment
augmentation_search_space: wide_standard
randaug:
  N: 0
  M: 0    # from appendix
  weights: [0.0,1.0]
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 5.0e-4
