model:
  type: shakeshake26_2x96d
dataset: cifar10
cutout: 16
batch: 64
gpus: 8
epoch: 1800
lr: 0.2
aug: randaugment
augmentation_search_space: fixed_standard
randaug:
  N: 0
  M: 0    # from appendix
  weights: [0.0,1.0]
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 4
    epoch: 10
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
