model:
  type: shakeshake26_2x96d
dataset: cifar10
cutout: 16
batch: 256
epoch: 1800
lr: 0.01
aug: randaugment
randaug:
  N: 3
  M: 9    # from appendix
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.001
