model:
  type: wresnet28_10
dataset: cifar100
aug: default
augmentation_search_space: fix_standard
cutout: 16
batch: 128
gpus: 1
epoch: 200
lr: 0.05
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

preprocessor:
  type: learned_random_randaugmentspace
  entropy_alpha: 0.
  hidden_dim: 1
  scale_entropy_alpha: .0
  online_tests_on_model: false
  q_zero_init: true
  q_residual: false
  scale_embs_zero_init: true
  normalize_reward: false # needs to be false since we only have a single reward here!
  importance_sampling: false
  label_smoothing_rate: .0
  possible_num_sequential_transforms: [1,2,3,4]
  sigmax_dist: false
  use_images_for_sampler: false
  uniaug_val: false
  oldpreprocessor_val: true
  exploresoftmax_dist: false
  aug_probs: true
  non_embedding_sampler: true
  scale_trainable: true

next_step_loss:

meta_opt:
  meta_optimizer:
    type: adam
    lr: .1
    beta1: .9
    beta2: .999
