model:
  type: wresnet28_10
dataset: svhncore
aug: randaugment
augmentation_search_space: fix_custom
custom_search_space_augs: ['auto_contrast',
                           'blur',
                           'brightness',
                           'color',
                           'contrast',
                           'posterize',
                           'sharpness',
                           'shear_x',
                           'shear_y',
                           'translate_x',
                           'translate_y']
randaug:
  N: 0
  M: 0    # from appendix
  weights: [0.0,1.0]
cutout: 16
batch: 128
gpus: 1
epoch: 200
lr: 0.0025
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.005

