model:
  type: wresnet28_10
dataset: cifar100
aug: randaugment
randaug:
  N: 0
  M: 0    # from appendix
  weights: [0.0,1.0]
cutout: 16
batch: 128
gpus: 1
augmentation_search_space: fix_custom
custom_search_space_augs: ['auto_contrast', 'translate_y', 'equalize', 'flip_lr', 'sharpness', 'cutout', 'posterize', 'solarize', 'crop_bilinear', 'flip_ud', 'max_', 'contour']
epoch: 200
lr: 0.05
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

