model:
  type: wresnet28_10

dataset: cifar10
cutout: 16
aug: randaugment
augmentation_search_space: fixed_standard
randaug:
  N: 0
  M: 0    # from appendix


batch: 96
gpus: 8
epoch: 200
lr: 0.05
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 6
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005