model:
  type: wresnet28_10
dataset: cifar100
aug: default
cutout: 16
batch: 256
epoch: 200
lr: 0.05

lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5

optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

finite_difference_loss: true
model_meta_gradient: true
