model:
  type: wresnet28_10
  adaptive_dropouter:
    hidden_size: 100
    relu: true
    simple_dropout: false
    out_bias: true
    target_p: .8
    cross_entropy_alpha: .001
    inference_dropout: false
dataset: cifar10
cutout: 16
aug: default

preprocessor:
  type: learned_random_randaugmentspace
  entropy_alpha: 0.
  hidden_dim: 100
  scale_entropy_alpha: .0
  online_tests_on_model: false
  q_zero_init: true
  q_residual: false
  scale_embs_zero_init: true
  normalize_reward: true
  importance_sampling: false
  label_smoothing_rate: .0
  possible_num_sequential_transforms: [1,2,3,4]

alignment_loss:
  summation: standard
  align_with: '2'
  val_share: .0
  alignment_type: dot

meta_opt:
  meta_optimizer:
    type: adam
    lr: .001
    beta1: .0
    beta2: .999
batch: 128
epoch: 1000
lr: 0.05
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005