model:
  type: wresnet28_10
dataset: cifar10
aug: randaugment
randaug:
  N: 0
  M: 0    # from appendix
  weights: [0.0,1.0]
cutout: 16
batch: 256
gpus: 1
augmentation_search_space: ohl
augmentation_parameter_max: 2
epoch: 300
lr: 0.4
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 4
    epoch: 2
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001


clip: 3
smooth: .05
