model:
  type: wresnet28_10
dataset: cifar10
cutout: 16
aug: randaugment
adaptive_trainloader: null
randaug:
  N: 3
  M: 5     # from appendix
meta_opt:
  meta_optimizer:
    type: adam
    lr: .001
    beta1: .0
    beta2: .999
alignment_loss:
  summation: standard
  align_with: '2'
  val_share: .0
  alignment_type: dot


batch: 118
val_batch: 10
epoch: 300
lr: 0.05
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005