model:
  type: wresnet40_2
dataset: cifar10
aug: randaugment
randaug:
  N: 0
  M: 0    # from appendix
cutout: 16
gpus: 4
batch: 64
epoch: 200
augmentation_search_space: long_wide
lr: 0.05
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005