model:
  type: wresnet28_10
  weight_norm: true
dataset: cifar100
aug: default
cutout: 16
batch: 256
epoch: 200
lr: 3.0e-3

lr_schedule:
  type: 'constant'

optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

finite_difference_loss: true
model_meta_gradient: true
