model:
  type: wresnet28_10
dataset: cifar10
cutout: 16
aug: default
batch: 128
epoch: 300
lr: 0.05
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005