model:
  type: wresnet28_10
dataset: cifar100
aug: default
cutout: 16
batch: 256
epoch: 200
lr: 0.05

lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5

optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

finite_difference_loss: true

preprocessor:
  type: learned_1x1conv
  hidden_dim: 100
  uniaug_val: false
  oldpreprocessor_val: false

meta_opt:
  meta_optimizer:
    type: adam
    lr: .001
    beta1: .0
    beta2: .999
