model:
  type: wresnet28_10
  weight_norm: true
  adaptive_modulator:
    hidden_size: 100
    relu: true
    out_bias: true
dataset: cifar100
aug: default
cutout: 16
batch: 256
epoch: 200
lr: 0.05

lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5

optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

finite_difference_loss: true

meta_opt:
  meta_optimizer:
    type: adam
    lr: .0001
    beta1: .0
    beta2: .999
