model:
  type: wresnet28_10
dataset: cifar100
aug: randaugment
augmentation_search_space: randaug_standard
randaug:
  N: 0
  M: 0    # from appendix
cutout: 16
batch: 256
epoch: 200
lr: 0.05
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

