model:
  type: wresnet28_10
  weight_norm: true
dataset: cifar100
aug: default
cutout: 16
batch: 10
epoch: 1
lr: 0.01

lr_schedule:
  type: 'constant'

optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

finite_difference_loss: true

preprocessor:
  type: learned_1x1conv
  hidden_dim: 100
  uniaug_val: false
  oldpreprocessor_val: false

meta_opt:
  meta_optimizer:
    type: adam
    lr: .01
    beta1: .0
    beta2: .999
