model:
  type: wresnet28_10
dataset: cifar10
aug: randaugment
randaug:
  N: 0
  M: 0    # from appendix
  weights: [0.0,1.0]
cutout: 16
batch: 128
gpus: 8
augmentation_search_space: fixed_standard
epoch: 1600
lr: 0.2
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 4
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

