model:
  type: wresnet28_10
  groupnorm: true
dataset: cifar10
aug: randaugment
randaug:
  N: 0
  M: 0    # from appendix
cutout: 16
batch: 128
epoch: 200
lr: 0.05
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005